# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDEPGeoservicios
                                 A QGIS plugin
 El siguiente plugin, tiene como finalidad brindar acceso a los servicios geoespaciales de las instituciones públicas del Perú.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-27
        copyright            : (C) 2024 by PCM - SGTD - IDEP
        email                : lrodriguez@pcm.gob.pe
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
# noinspection PyPep8Naming
def classFactory(iface):
    from .main import QGISWebScraper
    return QGISWebScraper(iface)
