# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QGISWebScraperLayerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets , QtGui


class Ui_QGISWebScraperLayerDialog(object):
    def setupUi(self, QGISWebScraperLayerDialog):
        QGISWebScraperLayerDialog.setObjectName("QGISWebScraperLayerDialog")
        QGISWebScraperLayerDialog.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(QGISWebScraperLayerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layerTreeWidget = QtWidgets.QTreeWidget(QGISWebScraperLayerDialog)
        self.layerTreeWidget.setObjectName("layerTreeWidget")
        self.verticalLayout.addWidget(self.layerTreeWidget)
        self.addLayerButton = QtWidgets.QPushButton(QGISWebScraperLayerDialog)
        self.addLayerButton.setObjectName("addLayerButton")
        self.verticalLayout.addWidget(self.addLayerButton)

        self.retranslateUi(QGISWebScraperLayerDialog)
        QtCore.QMetaObject.connectSlotsByName(QGISWebScraperLayerDialog)

    def retranslateUi(self, QGISWebScraperLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        QGISWebScraperLayerDialog.setWindowTitle(_translate("QGISWebScraperLayerDialog", "IDEPGeoServices"))
        self.layerTreeWidget.headerItem().setText(0, _translate("QGISWebScraperLayerDialog", "Nombre de capa"))
        self.layerTreeWidget.headerItem().setText(1, _translate("QGISWebScraperLayerDialog", "Título de capa"))
        self.addLayerButton.setText(_translate("QGISWebScraperLayerDialog", "Cargar capa selecionada"))
